@host = localhost:5283
@restaurantId = 1
@token = CfDJ8GJj8HFoiZdAq9cWYSCoG-YUn1tSss2kmKUWmXEQVy1o657mR-adyHPQKImT4PvcLDSg2jWuLARwnwfZrWcCWtsi3ZESnq29lSouWo1C6yExzX4mNl58qnfZpekHJphBQtbeOaUr-J3q-1zjlVPBdGLl-SrgOXqDjQ7WB4QmLilQbJ_FHn81SVlX_4iPZ5HjFPG0ISEC9heF0pwebW02TtdISIegphgDSUhTvQiokJHneBRXW_aIl3nzowoyM0vNEg76DBFR9Aa7ZC6KDKYclsa0Tz75mLaufLPzfzzQFNVeEcT3Dy5NA2O3YyAFeyyXsUIGNJgmmuzR2bv--UT5-TLrbmgt5Y42pvZXCnMPZcLidNc_RsCxOYGAGOuzxTONp2D-O0SlURCtHSjczfEnSp9uYgrUwOCTQfjOm1POJgVZV7yCGnB5JCcOnlqJ-zQ9ohS5Sbps5uwPjX8EDK9Fi6TSzrpvdmcP0SIchKTHsbo0NwnnpRz_rcO-LDvURmFsVJ0a_BMeuQppU2D7Bu00DOLUiEy_LTVxi_9AvgC-atT-AIgN6C5OC3TBKjry_76P6zYVuqRfVADWC5jedkRWoPniNyBzDYnYofoUfJIQkA7-JvMud_FXINlG9AStaiol0fnZfWHFZfHoOgbW0lQNYx1xZDtyWpWOI0hpiCuiRL6NJfshZDMmhIJZWhH3dV_sZvquVTsXf1RZlwHOu9Am60kqZ3gVDyZl9g0r7buQXSlj1uuRN1OCud7OobqzV7Cgzjm_yG7PpL57Qi6ECmtWplix-W5EnaGW1MHQQqFYZcmx

GET http://{{host}}/api/restaurants
Accept: application/json
Authorization: Bearer {{token}}

###

GET http://{{host}}/api/restaurants/1
Accept: application/json
Authorization: Bearer {{token}}

###

GET http://{{host}}/api/restaurants/123
Accept: application/json
Authorization: Bearer {{token}}

###

POST http://{{host}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Name": "Owner2 restaurant2",
    "Description": "A cozy restaurant serving a variety of delicious dishes.",
    "Category": "Italian",
    "HasDelivery": true,
    "ContactEmail": "info@test.com",
    "ContactNumber": "555-1234",
    "City": "New York",
    "Street": "123 Main Street",
    "PostalCode": "10-010"
}

###

POST http://{{host}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Name": "Owner2 restaurant2",
    "Description": "postal code wrong - email wrong = validation should prevent from adding this restaurant.",
    "Category": "Indian",
    "HasDelivery": true,
    "ContactEmail": "testtest.info",
    "ContactNumber": "555-1234",
    "City": "New York",
    "Street": "123 Main Street",
    "PostalCode": "10010"
}

###

PATCH http://{{host}}/api/restaurants/5
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Name": "PWNed",
    "Description": "description patched!!!!",
    "HasDelivery": false

}

###

DELETE http://{{host}}/api/restaurants/1
Accept: application/json
Authorization: Bearer {{token}}

###
POST http://{{host}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Name": "Mc Spaghetti",
    "Description": "Spaghetti but MC fashioned",
    "Price": 25.99
}

###
GET http://{{host}}/api/restaurants/1/dishes/1
Authorization: Bearer {{token}}

###
POST http://{{host}}/api/identity/register
Content-Type: application/json

{
    "email": "user@outlook.com",
    "password": "Qwerty123!"
}

###
POST http://{{host}}/api/identity/login
Content-Type: application/json

{
    "email": "owner@outlook.com",
    "password": "Qwerty123!"
}
