@host = localhost:5283

GET http://{{host}}/api/restaurants
Accept: application/json

###

GET http://{{host}}/api/restaurants/1
Accept: application/json

###

GET http://{{host}}/api/restaurants/123
Accept: application/json

